name: eden_learning_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_screenutil: ^5.7.0
  flutter_svg: ^2.0.5
  surf_lint_rules: 
  smooth_page_indicator: ^1.1.0
  animate_do: ^3.0.2
  flutter_swipe_button: ^2.1.1+1
  confetti: ^0.7.0
  flutter_staggered_animations: 
  fl_chart: 
  html: 
  http: 
  intl: 
  introduction_screen: 
  modal_progress_hud_nsn: 
  model_viewer_plus: 
  provider: 
  sizer: 
  webview_flutter: 

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/

  fonts:
    - family: Hanken Grotesk
      fonts:
        - asset: assets/fonts/HankenGrotesk-Regular.ttf
        - asset: assets/fonts/HankenGrotesk-Bold.ttf
        - asset: assets/fonts/HankenGrotesk-ExtraLight.ttf
        - asset: assets/fonts/HankenGrotesk-Light.ttf
        - asset: assets/fonts/HankenGrotesk-Medium.ttf


